### ISSUE TITLE
Ověření výsledného textu

### ISSUE THREAD

**Issue by pdostal** [HlidacStatu/OcrMinion#13]
Ahoj,

nikde jsem se to nedočetl a tak se zeptám tady: Jak se ověřuje výsledný text z obrázku?
Napadají mě dva problémy: 1) Přesnost OCR softwaru 2) Záměrně podvrhnutý text
Bylo by třeba fajn vše konvertovat vícekrát a z výsledků vytvářet kontrolní diff.

**Comment by suchoss** [comment]
Ahoj, díky. Už řešíme tady:
https://github.com/HlidacStatu/OcrMinion/issues/10
