### ISSUE TITLE
OCR Minion jako BOINC project

### ISSUE THREAD

**Issue by martinsuchan** [HlidacStatu/OcrMinion#14]
Sleduji diskuzi o OCR Minionu, zejména nedávné otázky, jak validovat správnost výsledků po zapojení již více než 1000 instancí, a jako jedno řešení mě napadlo - jak složité by bylo **nasadit OCR Miniona jako plnohodnotný BOINC projekt**?

**Co je BOINC - [Berkeley Open Infrastructure for Network Computing](https://boinc.berkeley.edu/trac/wiki/ProjectMain)?**
Roky osvědčená platforma pro řešení distribuovaných výpočtů, která vyrostla jako evoluce pilotního projektu SETI@home. Ten asi znáte, uživatel si stáhl aplikaci, pomocí které mohl jeho počítač hledat "signály mimozemšťanů z vesmíru". Fungovalo to tak, že si appka vždy stáhla záznam šumu z radioteleskopu, tam několik hodin hledala silnější signály. To u jednoho tasku trvalo třeba 5-10 hodin. Poté appka odeslala výsledek a stáhla si nový úkol. Je to hodně podobný princip, jak aktuální OCR Minion.

SETI@home vedlo ke vzniku platformy BOINC. U té si uživatel stáhne BOINC klientskou appku, zvolí si, do jakých vědeckých projektů se chce zapojit, a zbytek řeší appka za něho.
Appka má široké možnosti konfigurace, volbu, kolik % CPU, RAM a HDD mohou projekty využít, jak často mají běžet, na jak dlouho dopředu stahovat práci, pokud bývá PC často bez Internetu, jak často střídat projekty, kolik % výkonu půjde jakému projektu, kdy se připojovat k Internetu a mnohem více.
Samotný BOINC řeší i velkou řadu problémů, která souvisí s distribuovanými výpočty - distribuci různých verzí aplikací pro různé typy OS a HW (linux/Windows, x86/x64, tasky pro GPU, CUDA...), update aplikací na nové verze, validaci stažených pracovních jednotek, přepínání mezi tasky, validace výsledků, jejich posílání zpět. Dále také client side a server side rušení tasků, handlování náhodných chyb, které se stanou třeba při nečekaném vypnutí počítače, a systémových chyb, pokud některá pracovní jednotka všem uživatelům "padá", validaci výsledků pomocí kvora na serveru, aby se předešlo úmyslným i neúmyslným chybám, atd.
Jako bonus potom BOINC nabízí i gamifikaci v podobě správy uživatelů, týmů, různé žebříčky podle počtu zpracovaných tasků, počtu hodin, atd.

Samotné založení serveru bývalo celkem komplikované, ale poslední dobou je dostupný i tento **návod, jak si nasadit vlastní BOINC server jako docker instanci během pár minut**, který jsem si sám vyzkoušel:
https://github.com/marius311/boinc-server-docker/blob/master/docs/cookbook.md
Dále popisuje nasazení vlastní appky, generování tasků a zpracování výsledků. Většina funguje hezky "out of the box".

Asi by to byla práce na několik dnů až týnů si to vše projít a zapojit na data z Hlídače státu, ale pokud se s OCR minionem počítá více do budoucna, mohla by tato cesta ušetřit dost práce, než znova vynalézat kolo a řešit vše po svém.

**Comment by suchoss** [comment]
Určitě je to zajímavý nápad. Osobně by mě to zajímalo, ale časově to nedám. Pokud se Ti chce do toho jít, tak klidně můžeš. Pokud bys od nás k tomu něco potřeboval, tak dej vědět.
