### ISSUE TITLE
Pripravit container pro ARM procesory

### ISSUE THREAD

**Issue by michalblaha** [HlidacStatu/OcrMinion#4]
zatim je dostupny pouze pro Intel.

**Comment by bendaja** [comment]
Pokud by byl zájem, připravil jsem DockerFile pro arm32v7 (armhf), tedy je to spustitelné na Raspberry Pi (zkouším 3B). Jen nevím, jak to otestovat. Nerad bych to spouštěl "na ostro", tedy spustil jsem s parametem OCRM_DEMO=true, zdá se, že to žije (loguje to pravidelně warn: HlidacStatu.OcrMinion.Program[0] Returned task is invalid. null), ale nevím, jak do toho dostat něco užitečného.

**Comment by suchoss** [comment]
@bendaja Zájem by určitě byl. :) Domluvím se s Michalem a dám vědět co a jak. Díky

**Comment by suchoss** [comment]
@bendaja Ahoj, omlouvám se za delší prodlevu. Chce se Ti ještě připravit ten Dockerfile pro arm? Díky

**Comment by mpavlikWandera** [comment]
bylo by mozne pripravit image pro Apple s M1 procesory? 

`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

**Comment by suchoss** [comment]
Ahoj @mpavlikWandera Můžu se o to pokusit. Dám si to do úkolů. Snad se mi podaří se k tomu dostat tento týden.

**Comment by suchoss** [comment]
@mpavlikWandera prozatím, než se dostanu k buildování, nepomohlo by to spustit s parametrem `--platform linux/amd64` ?

**Comment by suchoss** [comment]
@mpavlikWandera Připravil jsem `ocrminion:v2.2`, který by měl zvládat `linux/amd64` a `linux/arm64` . Můžeš ho prosím vyzkoušet?

**Comment by radeksimko** [comment]
@suchoss Díky - za mě funguje na M1 Macu (host machine)! 👍🏻 

Off Topic otázka: Můžu to rovnou pustit ve více instancích, nebo na to backend není ještě ready? Nerad bych to přehltil 😄

**Comment by radeksimko** [comment]
A ještě si dovolím jednu OT: Plánuje(te/š) publikovat [BlurredPage Minion](https://hub.docker.com/r/hlidacstatu/blurred_page_minion/tags) taky pro ARM?

**Comment by suchoss** [comment]
@radeksimko Já to také teď testuju na M1. Zatím ale bohužel nebyly ve frontě žádné tasky na zpracování - máme zpracováno 😄 , takže čekám až se mi tam něco objeví na tesseract.

Ve více instancích to pustit můžeš, ale asi je to zbytečné. Momentálně máme fronty prázdné, takže jedna instance bude stačit :). Zatím šetři svého miláčka, zítra (tam je to možná trochu složitější s knihovnama, takže to budu muset víc otestovat) snad budu mít hotového BlurredPage miniona, který aktuálně potřebujeme trochu víc 😃

**Comment by suchoss** [comment]
Update:
Funguje na M1

Blurred page minion bude složitější - řeším knihovny
