### ISSUE TITLE
Returned task is invalid.

### ISSUE THREAD

**Issue by exyi** [HlidacStatu/OcrMinion#5]
Je normální, že je log plný tohoto?

```
warn: HlidacStatu.OcrMinion.Program[0]
      Returned task is invalid. 
      null
```

Jestli ne, tak to můžu zkusit zdebugovat pořádněji. Trochu čekám, že to jenom znamená, že nedostal nic na práci.

<details><summary>Toto je celý log od startu kontejneru</summary>

(a ano, klíče jsem vymazal :slightly_smiling_face:)

```
app is down
Loaded configuration:
  OCRM_APIKEY=XXXX
  OCRM_EMAIL=XXXX
  OCRM_DEMO=False
  base_address=https://ocr.hlidacstatu.cz
  user_agent=OcrMinion
info: HlidacStatu.OcrMinion.Program[0]
      OCR minion initialized.
info: HlidacStatu.OcrMinion.Program[0]
      Getting new image.
warn: HlidacStatu.OcrMinion.Program[0]
      Returned task is invalid. 
      null
warn: HlidacStatu.OcrMinion.Program[0]
      Returned task is invalid. 
      null
warn: HlidacStatu.OcrMinion.Program[0]
      Returned task is invalid. 
      null
warn: HlidacStatu.OcrMinion.Program[0]
      Returned task is invalid. 
      null
warn: HlidacStatu.OcrMinion.Program[0]
      Returned task is invalid. 
      null
warn: HlidacStatu.OcrMinion.Program[0]
      Returned task is invalid. 
      null
warn: HlidacStatu.OcrMinion.Program[0]
      Returned task is invalid. 
      null
warn: HlidacStatu.OcrMinion.Program[0]
      Returned task is invalid. 
      null
warn: HlidacStatu.OcrMinion.Program[0]
      Returned task is invalid. 
      null
warn: HlidacStatu.OcrMinion.Program[0]
      Returned task is invalid. 
      null
warn: HlidacStatu.OcrMinion.Program[0]
      Returned task is invalid. 
      null
warn: HlidacStatu.OcrMinion.Program[0]
      Returned task is invalid. 
      null
info: HlidacStatu.OcrMinion.Program[0]
      Image for task[435021ff-0013-4b7b-80c3-956537896fe2] successfully downloaded.
info: HlidacStatu.OcrMinion.Program[0]
      Starting OCR process of #1. task.
info: HlidacStatu.OcrMinion.Program[0]
      Getting new image.
warn: HlidacStatu.OcrMinion.Program[0]
      Returned task is invalid. 
      null
info: HlidacStatu.OcrMinion.Program[0]
      OCR process of #1. task successfully finished.
warn: HlidacStatu.OcrMinion.Program[0]
      Returned task is invalid. 
      null
warn: HlidacStatu.OcrMinion.Program[0]
      Returned task is invalid. 
      null
warn: HlidacStatu.OcrMinion.Program[0]
      Returned task is invalid. 
      null
warn: HlidacStatu.OcrMinion.Program[0]
      Returned task is invalid. 
      null
warn: HlidacStatu.OcrMinion.Program[0]
      Returned task is invalid. 
      null
warn: HlidacStatu.OcrMinion.Program[0]
      Returned task is invalid. 
      null
warn: HlidacStatu.OcrMinion.Program[0]
      Returned task is invalid. 
      null
warn: HlidacStatu.OcrMinion.Program[0]
      Returned task is invalid. 
      null
```

</details>

**Comment by pstast** [comment]
Já to mám stejně. Většina pokusů o stažení nového tasku skončí chybou:
```
warn: HlidacStatu.OcrMinion.Program[0]
      Returned task is invalid. 
      null
```
Jen výjimečně se nějaký task stáhne a vykoná, takže většinu času to nedělá nic.

**Comment by vpekarek** [comment]
U mě stejné. Během hodiny a půl úspěšně stažené dvě stránky. 
Spuštěno na Synology DS218+

**Comment by suchoss** [comment]
Ahoj, tohle je v pořádku - znamená to, že aktuálně na serveru není obrázek k dispozici. Budu muset přidat lepší chybovou hlášku.

**Comment by obud** [comment]
Ahoj, také se přimlouvám za lepší hlášku. Snad by ani nemusela být typu "warn", ale jen "info". Díky.

**Comment by pstast** [comment]
A proč, přestože dle statistik např. nyní "dalších 966 scanů čeká ve frontě", se mé OcrMinion procesy zcela nudí a většina požadavků skončí "Returned task is invalid", tedy není co dělat?

Na Twitteru se dnes píše "Chvilku to trvalo, ale asi poprvé se nám podařilo vytížit všechny OCR Miniony. Díky za pomoc!". Ale to není pravda. Mé se zcela nudí a nedočkavé procesory zahálí.

Má to souvislost s férovým rozdělením úkolů mezi různé uživatele (API klíče)?

**Comment by suchoss** [comment]
@pstast  Koukám, že @michalblaha omylem odpověděl k jinému issue, tak vkládám odpověď sem:

> Ma to tyto duvody
> 
> statistika na webu je cachovana 2 minuty, takze je vetsinou pomerne zpozdena. Duvodem je snizeni zateze na tuto statistiku na SQL serveru
> lehce jsme omezili pridelovani ukolu, a to tak, ze jsou pridelovany nejdrive po 3 sekundach, nekdy drive.
> porad plati, ze OCR miniony jsou rychlejsi, nez pridelovani ukolu. Je to dane charakterem dokumentu, ktere se ted prave zpracovavaji (vetsina jde vydolovat mimo OCR Minion naprimo) a jsou pomerne kratke.

**Comment by suchoss** [comment]
Zapracováno do nové verze v2.0. Brzy bude release.
