### ISSUE TITLE
Informace o minimálních požadavcích

### ISSUE THREAD

**Issue by Vrtak-CZ** [HlidacStatu/OcrMinion#6]
Jaké jsou minimální požadavky pro běh?
Kolik RAM?
Kolik CPU?
Je více jader lépe?
Je lepší pustit více containerů s jedním jádrem nebo jeden s mnoha jádry?

**Comment by Vrtak-CZ** [comment]
Odpovím si částečně sám:

> Tesseract 4 also uses up to four CPU threads while processing a page

viz https://github.com/tesseract-ocr/tesseract/wiki/FAQ#can-i-increase-speed-of-ocr

nicméně info ohledně RAM jsem zatím nenašel

**Comment by suchoss** [comment]
@Vrtak-CZ Aplikace samotná OcrMinion by měla používat jen minimum prostředků, RAM je myslím kolem 35 MB. Alpine linux je také nenáročný. Největším žroutem je právě Tesseract-ocr.

S Tesseractem zatím nemám moc zkušeností. Možná by mohl poradit někdo, kdo bude vědět víc.
