### ISSUE TITLE
Omezení běhu časem/počtem

### ISSUE THREAD

**Issue by soukicz** [HlidacStatu/OcrMinion#8]
Jak moc komplikované by bylo přidat režim, který buď zpracovává po určitém počtu obrázků a skončí nebo bude mít třeba nastavenou dobu běhu?

Řeším totiž, že na https://shopapi.cz/ používáme AWS Batch, ale jsou tam prodlevy - není co zpracovávat, ale zároveň se nevyplatí instance vypínat. Jednoduše bych mohl doplnit, aby se do takových prostojů mezi komerční joby doplnilo OCR, ale potřebuju to nějak omezit, abych tím mohl vyplňovat třeba 10ti minutové bloky na různých strojích. V aktuální podobě bych to jedině musel zabíjet a to by asi zase nechávalo rozpracované job ve frontě.

Případně když container zabiju, zpracovává to nějak signály, že by to dojelo aktuální obrázek?

**Comment by suchoss** [comment]
Zatím to není nastavené, aby to dojelo aktuální obrázek. Vidím dvě možnosti:
1) přidat tam časovač, po jakou dobu to má běžet - tohle není úplně mnou preferovaná varianta, ale asi bych to zkousnul.  
2) při zavolání docker stop můžu nastavit, že to bude přijímat SIGTERM (https://www.ctl.io/developers/blog/post/gracefully-stopping-docker-containers/) a požádat aplikaci o ukončení, ale protože tesseract běží většinou déle než 10 vteřin (u mě obrázek trvá cca minutu), tak by bylo potřeba container ukončovat pomocí docker stop -t 60

Jiné návrhy? Případně která varianta by byla lepší?

**Comment by soukicz** [comment]
Druhá varianta zní dobře. První řeší můj specifický výmysl, zatímco druhá by asi rovnou vyřešila i další situace. Časované vypnutí si pak můžu doplnit na svojí straně, když to bude podporovat opatrné vypnutí.

**Comment by suchoss** [comment]
Přidáno graceful termination. Není nutné nastavovat -t na delší dobu než je default.
